### ISSUE TITLE
Low perf with single connection 

### ISSUE THREAD

**Issue by shreenidhihegde** [h2o/h2o#1125]
Hi,

I am using h20 library as HTTP Server for my application. 

I am running on low performance when I use 1 connection and 1 thread in wrk tool. Even when tried manually the consecutive third request's response is not received until another application (using consul health check request) spawns a new request and writes into socket.
  

/home/shegde/wrk -t1  -c1 -d30s -s ./post.lua https://localhost:40134/<application url>
Running 30s test @ https://localhost:40134/<application url>
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   495.43ms  410.26ms   1.02s    33.33%
    Req/Sec     2.15      2.65    10.00     90.91%
  61 requests in 30.03s, 14.24KB read
Requests/sec:      2.03
Transfer/sec:     485.42B

I have keep-alive option enabled and using TCP_NODELAY option. I am getting better performance when number of connections increase. I want to get better perf lower connection.

Also, My h2o version is older (around an year), when I tried upgrading h2o to latest I ended up with compilation error as my openssl version is OpenSSL 1.0.1e-fips 11 Feb 2013.

Appreciate your help on this.

Thanks,
Shreenidhi

**Comment by shreenidhihegde** [comment]
further more investigation leads me to
395         if ((entity_body_header_index = fixup_request(conn, headers, num_headers, minor_version, &expect)) != -1) {
396             if (expect.base != NULL) {
397                 if (!h2o_lcstris(expect.base, expect.len, H2O_STRLIT("100-continue"))) {
398                     set_timeout(conn, NULL, NULL);
399                     h2o_socket_read_stop(conn->sock);
400                     h2o_send_error(&conn->req, 417, "Expectation Failed", "unknown expectation",
401                                    H2O_SEND_ERROR_HTTP1_CLOSE_CONNECTION);
402                     return;
403                 }
404                 static const h2o_iovec_t res = {H2O_STRLIT("HTTP/1.1 100 Continue\r\n\r\n")};
405                 h2o_socket_write(conn->sock, (void *)&res, 1, on_continue_sent);
406             }
407             if (create_entity_reader(conn, headers + entity_body_header_index) != 0) {
408                 return;
409             }
410             if (expect.base != NULL) {
411                 /* processing of the incoming entity is postponed until the 100 response is sent */
412                 h2o_socket_read_stop(conn->sock);
413                 return;
414             }
415             conn->_req_entity_reader->handle_incoming_entity(conn);
416         } else {
417             set_timeout(conn, NULL, NULL);
418             h2o_socket_read_stop(conn->sock);   <<<<<<<< this is causing the socket  to stop reading read as fixup_request did not respond with -1.
419             process_request(conn);
420         }


When I comment out the line 418 Im getting considerable good perf.

**Comment by deweerdt** [comment]
@shreenidhihegde could you try to compile current master with `cmake -DWITH_BUNDLED_SSL=ON .` ? That might help you address the issue of compiling a more recent h2o. Also, which OS are you running on?

**Comment by shreenidhihegde** [comment]
@deweerdt 👍  I will try that. Thanks. My OS is redhat Linux.

**Comment by kazuho** [comment]
@shreenidhihegde 
> on_entity_read_complete callback is stopping socket read.

That is the expected behavior. Read is resumed when your application completes sending a response (please see on_send_complete invoking reqread_start).

**Comment by shreenidhihegde** [comment]
@kazuho : ok..
I also notice that
Breakpoint 3, proceed_handshake (sock=0x7fdc5d514500, status=-1) at contrib/opensource/h2o/lib/common/socket.c:461
461     in contrib/opensource/h2o/lib/common/socket.c
(gdb) bt
#0  proceed_handshake (sock=0x7fdc5d514500, status=-1) at contrib/opensource/h2o/lib/common/socket.c:461
#1  0x00000000016e3928 in read_on_ready (sock=0x7fdc5d514500) at contrib/opensource/h2o/lib/common/socket/evloop.c.h:249
#2  run_socket (sock=0x7fdc5d514500) at contrib/opensource/h2o/lib/common/socket/evloop.c.h:487
#3  0x00000000016e4b36 in run_pending (loop=<optimized out>) at contrib/opensource/h2o/lib/common/socket/evloop.c.h:498
#4  h2o_evloop_run (loop=0x7fdc2dcc6500) at contrib/opensource/h2o/lib/common/socket/evloop.c.h:511


proceed_handshake has status = -1, that means read resulted into error. Is this the cause for socket closure? we are using non-blocking socket, we are bound to get socket errors like EAGAIN/EWOULDBLOCK.
