### ISSUE TITLE
h2o proxy crashed with h2load large resource

### ISSUE THREAD

**Issue by tatsuhiro-t** [h2o/h2o#122]
I frequently experience h2o proxy crashed if we perform h2load with relatively large GET (128k bytes file),
like this:
```
h2load -n100000 -c100 -m100 http://localhost:3000/128k -w30 -W30
```

Then h2o crashed with following message:
```
h2o server (pid:2084) is ready to serve requests
h2o: /path/h2o/lib/http2/connection.c:930: do_emit_writereq: Assertion `conn->_write.buf_in_flight == ((void *)0)' failed.
```

The test was done without TLS.

**Comment by kazuho** [comment]
Thank you for reporting the issue. Would you mind describing the test configuration a bit more(e.g. what is the upstream server, is keep-alive used, etc.)?

There is a unit test that transfers a 50MB file to/from the proxy under various configurations, and the test has not reported such error for some time.  That leads me to think this issue as timing or configuration-related, that is why I would like to know the details.

**Comment by tatsuhiro-t** [comment]
Here is the h2o.conf:
```
# to find out the configuration commands, run: h2o --help

listen:
  port: 3000
num-threads: 1
hosts:
  default:
    paths:
      /:
        proxy.reverse.url: http://127.0.0.1:18100
        proxy.keepalive: ON
```
The backend server is nginx 1.7.8, running on the same host and at port 18100.

I ran h2o like this:
```
$ ./h2o -c examples/h2o-bug.conf
[INFO] raised RLIMIT_NOFILE to 65536
h2o server (pid:12526) is ready to serve requests
```

Then in another terminal, start h2load:
```
$ h2load -n100000 -c100 -m100 http://localhost:3000/128k -w30 -W30
starting benchmark...
spawning thread #0: 100 concurrent clients, 100000 total requests

finished in 6 sec, 661 millisec and 90 microsec, 15012 req/s, 164256 kbytes/s
requests: 100000 total, 17450 started, 100000 done, 7450 succeeded, 92550 failed, 92550 errored
status codes: 17190 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 1120387002 bytes total, 131754 bytes headers, 1119411552 bytes data
```

You see many errors, because h2o crashed:
```
h2o: /path/h2o/lib/http2/connection.c:930: do_emit_writereq: Assertion `conn->_write.buf_in_flight == ((void *)0)' failed.
```

Here is gdb backtrace:
```
$ LANG=C gdb h2o core
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from h2o...done.
[New LWP 12527]
[New LWP 12526]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./h2o -c examples/h2o-bug.conf'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fbeb825f107 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007fbeb825f107 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fbeb82604e8 in __GI_abort () at abort.c:89
#2  0x00007fbeb8258226 in __assert_fail_base (
    fmt=0x7fbeb838e968 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x423b48 "conn->_write.buf_in_flight == ((void *)0)", 
    file=file@entry=0x423a48 "/path/h2o/lib/http2/connection.c", line=line@entry=930, 
    function=function@entry=0x4241d0 <__PRETTY_FUNCTION__.17534> "do_emit_writereq") at assert.c:92
#3  0x00007fbeb82582d2 in __GI___assert_fail (
    assertion=assertion@entry=0x423b48 "conn->_write.buf_in_flight == ((void *)0)", 
    file=file@entry=0x423a48 "/path/h2o/lib/http2/connection.c", line=line@entry=930, 
    function=function@entry=0x4241d0 <__PRETTY_FUNCTION__.17534> "do_emit_writereq") at assert.c:101
#4  0x000000000041663d in do_emit_writereq (conn=0x7fbeb0a357a0)
    at /path/h2o/lib/http2/connection.c:930
#5  0x000000000040bf5a in h2o_timeout_run (
    timeout=timeout@entry=0x7fbeb8228d58, now=now@entry=1422016313105)
    at /path/h2o/lib/common/timeout.c:36
#6  0x000000000040bfac in h2o_timeout_run_all (
    timeouts=timeouts@entry=0x7fbeb00008e0, now=1422016313105)
    at /path/h2o/lib/common/timeout.c:49
#7  0x0000000000409fc5 in h2o_evloop_run (loop=loop@entry=0x7fbeb00008c0)
    at /path/h2o/lib/common/socket/evloop.c.h:492
#8  0x000000000041d027 in run_loop (_unused=<optimized out>)
    at /path/h2o/src/main.c:1039
#9  0x00007fbeb87df0a4 in start_thread (arg=0x7fbeb8229700)
    at pthread_create.c:309
#10 0x00007fbeb830fccd in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) 
```

**Comment by kazuho** [comment]
Thank you for the details.  I will try to reproduce the issue.

**Comment by kazuho** [comment]
Succeeded in reproducing the issue.  Trying to fix.

**Comment by kazuho** [comment]
Although I have fixed the cause the crash with the prev. commit other problems still seem to exist.  Seems like I need to open separate issues for them.

* h2load emits some failures (which is likely an issue within the reverse proxy, as it has no such problem in case h2o is configured to serve the same file statically)
* h2o may report assertion failures when h2load is stopped by Ctrl-C

If you find any issues please let me know.  Thank you for your help.

**Comment by tatsuhiro-t** [comment]
Thank you for fixing this.  As for assertion failure on h2load ctrl-C, I commented on the original issue #61.

**Comment by kazuho** [comment]
Thank you for mentioning that. I must have missed it.  Reopened the issue.
