### ISSUE TITLE
h2o server doesn't respond to SIGTERM on FreeBSD 10.1R amd64

### ISSUE THREAD

**Issue by dch** [h2o/h2o#127]
Using same h2o.conf as https://github.com/h2o/h2o/issues/125 and latest master, h2o server doesn't stop when SIGTERM is sent. Common tools like https://www.freebsd.org/cgi/man.cgi?query=daemon send SIGTERM to request orderly shutdown of the spawned process.

SIGQUIT, SIGKILL of course work as they are not trapped.

```
wintermute# su -m www -c 'sh -c "/usr/sbin/daemon -c -p /var/run/h2o.pid /usr/local/bin/h2o  --conf /usr/local/etc/h2o/h2o.conf"'
wintermute# [OCSP Stapling] failed to execute /usr/local/share/h2o/fetch-ocsp-response:No such file or directory
[OCSP Stapling] disabled for certificate file:/usr/local/etc/h2o/server.crt
[INFO] raised RLIMIT_NOFILE to 940005
h2o server (pid:4103) is ready to serve requests
[OCSP Stapling] failed to execute /usr/local/share/h2o/fetch-ocsp-response:No such file or directory
[OCSP Stapling] disabled for certificate file:/usr/local/etc/h2o/server.crt

wintermute# pgrep -ilf h2o
4103 /usr/local/bin/h2o --conf /usr/local/etc/h2o/h2o.conf
4102 daemon: /usr/local/bin/h2o[4103]
wintermute# kill -TERM 4103
wintermute# pgrep -ilf h2o
4103 /usr/local/bin/h2o --conf /usr/local/etc/h2o/h2o.conf
4102 daemon: /usr/local/bin/h2o[4103]
wintermute# curl localhost
^C
wintermute# kill -QUIT 4103
wintermute# pgrep -ilf h2o
wintermute#
```

Given the hung curl, and looking at https://github.com/h2o/h2o/blob/master/src/main.c#L935 suggests the signal is handled but that something doesn't work with `notify_all_threads()`.

**Comment by dch** [comment]
some gdb info:

```
dch 😈  /u/l/e/h2o ❯❯❯sudo -u www gdb /usr/local/bin/h2o
GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...
(gdb) break graceful_shutdown
Breakpoint 1 at 0x41b7e4: file /home/dch/src/www/h2o/src/main.c, line 927.
(gdb) run
Starting program: /usr/local/bin/h2o
[New LWP 100992]
[OCSP Stapling] failed to execute /usr/local/share/h2o/fetch-ocsp-response:No such file or directory
[OCSP Stapling] disabled for certificate file:/usr/local/etc/h2o/server.crt
[INFO] raised RLIMIT_NOFILE to 940005
h2o server (pid:4243) is ready to serve requests
[OCSP Stapling] failed to execute /usr/local/share/h2o/fetch-ocsp-response:No such file or directory
[OCSP Stapling] disabled for certificate file:/usr/local/etc/h2o/server.crt
[New Thread 801c09c00 (LWP 101002/h2o)]

Program received signal SIGTERM, Terminated.
[Switching to Thread 801c09c00 (LWP 101002/h2o)]
0x000000080142db7a in select () from /lib/libc.so.7
(gdb) info thread
[New Thread 801c09800 (LWP 101001/h2o)]
[New Thread 801c09400 (LWP 101000/h2o)]
[New Thread 801c09000 (LWP 100999/h2o)]
[New Thread 801c08c00 (LWP 100998/h2o)]
[New Thread 801c08800 (LWP 100997/h2o)]
[New Thread 801c08400 (LWP 100996/h2o)]
[New Thread 801c08000 (LWP 100995/h2o)]
[New Thread 801c06400 (LWP 100992/h2o)]
  10 Thread 801c06400 (LWP 100992/h2o)  0x000000080140b8ba in nanosleep () from /lib/libc.so.7
  9 Thread 801c08000 (LWP 100995/h2o)  0x000000080142db7a in select () from /lib/libc.so.7
  8 Thread 801c08400 (LWP 100996/h2o)  0x000000080142db7a in select () from /lib/libc.so.7
  7 Thread 801c08800 (LWP 100997/h2o)  0x000000080142db7a in select () from /lib/libc.so.7
  6 Thread 801c08c00 (LWP 100998/h2o)  0x000000080142db7a in select () from /lib/libc.so.7
  5 Thread 801c09000 (LWP 100999/h2o)  0x000000080142db7a in select () from /lib/libc.so.7
  4 Thread 801c09400 (LWP 101000/h2o)  0x000000080142db7a in select () from /lib/libc.so.7
  3 Thread 801c09800 (LWP 101001/h2o)  0x000000080142db7a in select () from /lib/libc.so.7
* 2 Thread 801c09c00 (LWP 101002/h2o)  0x000000080142db7a in select () from /lib/libc.so.7
(gdb) backtrace
#0  0x000000080142db7a in select () from /lib/libc.so.7
#1  0x00000008010cfb32 in select () from /lib/libthr.so.3
#2  0x0000000000406796 in h2o_evloop_run (loop=0x803c0e000) at select.c.h:101
#3  0x000000000041b5a8 in run_loop (_unused=0x2d) at /home/dch/src/www/h2o/src/main.c:1040
#4  0x00000008010cd4f5 in pthread_create () from /lib/libthr.so.3
#5  0x0000000000000000 in ?? ()
(gdb) finish
Run till exit from #0  0x000000080142db7a in select () from /lib/libc.so.7

Breakpoint 1, graceful_shutdown (signo=15) at /home/dch/src/www/h2o/src/main.c:927
927	    conf.shutdown_requested = 1;
Current language:  auto; currently minimal
(gdb) info thread
  10 Thread 801c06400 (LWP 100992/h2o)  0x000000080140b8ba in nanosleep () from /lib/libc.so.7
  9 Thread 801c08000 (LWP 100995/h2o)  0x000000080142db7a in select () from /lib/libc.so.7
  8 Thread 801c08400 (LWP 100996/h2o)  0x000000080142db7a in select () from /lib/libc.so.7
  7 Thread 801c08800 (LWP 100997/h2o)  0x000000080142db7a in select () from /lib/libc.so.7
  6 Thread 801c08c00 (LWP 100998/h2o)  0x000000080142db7a in select () from /lib/libc.so.7
  5 Thread 801c09000 (LWP 100999/h2o)  0x000000080142db7a in select () from /lib/libc.so.7
  4 Thread 801c09400 (LWP 101000/h2o)  0x000000080142db7a in select () from /lib/libc.so.7
  3 Thread 801c09800 (LWP 101001/h2o)  0x000000080142db7a in select () from /lib/libc.so.7
* 2 Thread 801c09c00 (LWP 101002/h2o)  graceful_shutdown (signo=15) at /home/dch/src/www/h2o/src/main.c:927
(gdb) backtrace
#0  graceful_shutdown (signo=15) at /home/dch/src/www/h2o/src/main.c:927
#1  0x00000008010d247a in swapcontext () from /lib/libthr.so.3
#2  0x00000008010d2062 in sigaction () from /lib/libthr.so.3
#3  <signal handler called>
#4  0x000000080142db7a in select () from /lib/libc.so.7
#5  0x00000008010cfb32 in select () from /lib/libthr.so.3
#6  0x0000000000406796 in h2o_evloop_run (loop=0x803c0e000) at select.c.h:101
#7  0x000000000041b5a8 in run_loop (_unused=0x2d) at /home/dch/src/www/h2o/src/main.c:1040
#8  0x00000008010cd4f5 in pthread_create () from /lib/libthr.so.3
#9  0x0000000000000000 in ?? ()
(gdb) next
921	    for (i = 0; i != conf.num_threads; ++i)
(gdb)
922	        h2o_thread_notify(conf.thread_ids[i]);
(gdb)

Program received signal SIGCONT, Continued.
[Switching to Thread 801c08000 (LWP 100995/h2o)]
0x000000080142db7a in select () from /lib/libc.so.7
(gdb)
Single stepping until exit from function select,
which has no line number information.
[Switching to Thread 801c09c00 (LWP 101002/h2o)]
graceful_shutdown (signo=<value optimized out>) at /home/dch/src/www/h2o/src/main.c:921
921	    for (i = 0; i != conf.num_threads; ++i)
(gdb)
922	        h2o_thread_notify(conf.thread_ids[i]);
(gdb)

Program received signal SIGCONT, Continued.
[Switching to Thread 801c08400 (LWP 100996/h2o)]
0x000000080142db7a in select () from /lib/libc.so.7
(gdb)
Single stepping until exit from function select,
which has no line number information.
[Switching to Thread 801c09c00 (LWP 101002/h2o)]
graceful_shutdown (signo=<value optimized out>) at /home/dch/src/www/h2o/src/main.c:921
921	    for (i = 0; i != conf.num_threads; ++i)
(gdb)
922	        h2o_thread_notify(conf.thread_ids[i]);
(gdb)
[Switching to Thread 801c08400 (LWP 100996/h2o)]
0x000000080142e32c in memcpy () from /lib/libc.so.7
(gdb)
Single stepping until exit from function memcpy,
which has no line number information.
[Switching to Thread 801c08000 (LWP 100995/h2o)]
0x000000080142e32c in memcpy () from /lib/libc.so.7
(gdb)
Single stepping until exit from function memcpy,
which has no line number information.
[Switching to Thread 801c09c00 (LWP 101002/h2o)]
graceful_shutdown (signo=<value optimized out>) at /home/dch/src/www/h2o/src/main.c:921
921	    for (i = 0; i != conf.num_threads; ++i)
(gdb)
922	        h2o_thread_notify(conf.thread_ids[i]);
(gdb)

Program received signal SIGCONT, Continued.
[Switching to Thread 801c08c00 (LWP 100998/h2o)]
0x000000080142db7a in select () from /lib/libc.so.7
(gdb)
Single stepping until exit from function select,
which has no line number information.
[Switching to Thread 801c09c00 (LWP 101002/h2o)]
graceful_shutdown (signo=<value optimized out>) at /home/dch/src/www/h2o/src/main.c:921
921	    for (i = 0; i != conf.num_threads; ++i)
(gdb)
[Switching to Thread 801c08c00 (LWP 100998/h2o)]
0x000000080142e32c in memcpy () from /lib/libc.so.7
(gdb)
Single stepping until exit from function memcpy,
which has no line number information.
[Switching to Thread 801c09c00 (LWP 101002/h2o)]
graceful_shutdown (signo=29400064) at /home/dch/src/www/h2o/src/main.c:922
922	        h2o_thread_notify(conf.thread_ids[i]);
(gdb)

Program received signal SIGCONT, Continued.
[Switching to Thread 801c09000 (LWP 100999/h2o)]
0x000000080138f41d in sbrk () from /lib/libc.so.7
(gdb)
Single stepping until exit from function sbrk,
which has no line number information.
[Switching to Thread 801c09c00 (LWP 101002/h2o)]
graceful_shutdown (signo=<value optimized out>) at /home/dch/src/www/h2o/src/main.c:921
921	    for (i = 0; i != conf.num_threads; ++i)
(gdb)
922	        h2o_thread_notify(conf.thread_ids[i]);
(gdb)
921	    for (i = 0; i != conf.num_threads; ++i)
(gdb)
922	        h2o_thread_notify(conf.thread_ids[i]);
(gdb)
921	    for (i = 0; i != conf.num_threads; ++i)
(gdb)
922	        h2o_thread_notify(conf.thread_ids[i]);
(gdb)

Program received signal SIGCONT, Continued.
0x00000008013566ca in thr_kill () from /lib/libc.so.7
(gdb)
Single stepping until exit from function thr_kill,
which has no line number information.
0x00000008010d4081 in pthread_kill () from /lib/libthr.so.3
(gdb)
Single stepping until exit from function pthread_kill,
which has no line number information.
graceful_shutdown (signo=<value optimized out>) at /home/dch/src/www/h2o/src/main.c:921
921	    for (i = 0; i != conf.num_threads; ++i)
(gdb)
929	}
(gdb)
0x00000008010d247a in swapcontext () from /lib/libthr.so.3
(gdb)
Single stepping until exit from function swapcontext,
which has no line number information.
0x00000008010d1a00 in pthread_getspecific () from /lib/libthr.so.3
(gdb)
Single stepping until exit from function pthread_getspecific,
which has no line number information.
0x00000008010d24d2 in swapcontext () from /lib/libthr.so.3
(gdb)
Single stepping until exit from function swapcontext,
which has no line number information.

[hangs here]
```

AFAICT the correct signal is sent to all threads, I'm out of my gdb depth at this point though.

**Comment by kazuho** [comment]
Thank you for reporting the issue.  Successfully reproduced the issue on NetBSD (haven't tried FreeBSD).

**Comment by kazuho** [comment]
@dch I assume that the problem has been fixed in the commit above, which has now been merged to master.

I would appreciate it if you could try using it, and close the issue if the problem has been fixed.  Thank you in advance.

**Comment by dch** [comment]
@kazuho san perfect, thank you so much.

```
dch   /u/l/e/h2o ❯❯❯[OCSP Stapling] failed to execute /usr/local/share/h2o/fetch-ocsp-response:No such file or directory
[OCSP Stapling] disabled for certificate file:/usr/local/etc/h2o/server.crt
[INFO] raised RLIMIT_NOFILE to 940005
h2o server (pid:13816) is ready to serve requests
[OCSP Stapling] failed to execute /usr/local/share/h2o/fetch-ocsp-response:No such file or directory
[OCSP Stapling] disabled for certificate file:/usr/local/etc/h2o/server.crt
dch   /u/l/e/h2o ❯❯❯pgrep h2o
13816 /usr/local/bin/h2o --conf /usr/local/etc/h2o/h2o.conf
13815 daemon: /usr/local/bin/h2o[13816]
dch   /u/l/e/h2o ❯❯❯ sudo kill 13816
dch   /u/l/e/h2o ❯❯❯received SIGTERM, gracefully shutting down
dch   /u/l/e/h2o ❯❯❯pgrep h2o
dch   /u/l/e/h2o ❯❯❯
```
