### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by glensc** [h2o/h2o#1438]
crashes on startup, likely due some memory corruption

- h2o 2.2.2
- gcc 7.2.0
- [h2o.conf](https://github.com/h2o/h2o/blob/v2.2.2/examples/h2o/h2o.conf)

```

[root@dind h2o]# h2o -c h2o.conf
*** Error in `h2o': munmap_chunk(): invalid pointer: 0x0000000000587090 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7447c)[0x7f349b26447c]
/lib64/libc.so.6(+0x7aaae)[0x7f349b26aaae]
h2o[0x4570b3]
h2o(h2o_configurator_apply_commands+0xa6)[0x43a556]
h2o(h2o_configurator_apply+0x41)[0x43dee1]
h2o(main+0x5b1)[0x4279f1]
/lib64/libc.so.6(__libc_start_main+0xf1)[0x7f349b2105a1]
h2o(_start+0x2a)[0x42818a]
======= Memory map: ========
00400000-006c6000 r-xp 00000000 00:6b 7150                               /usr/sbin/h2o
008c5000-008c7000 r--p 002c5000 00:6b 7150                               /usr/sbin/h2o
008c7000-008cb000 rw-p 002c7000 00:6b 7150                               /usr/sbin/h2o
00bcf000-00d4b000 rw-p 00000000 00:00 0                                  [heap]
7f349adda000-7f349ade5000 r-xp 00000000 00:6b 2241                       /lib64/libnss_files-2.25.so
7f349ade5000-7f349afe4000 ---p 0000b000 00:6b 2241                       /lib64/libnss_files-2.25.so
7f349afe4000-7f349afe5000 r--p 0000a000 00:6b 2241                       /lib64/libnss_files-2.25.so
7f349afe5000-7f349afe6000 rw-p 0000b000 00:6b 2241                       /lib64/libnss_files-2.25.so
7f349afe6000-7f349afec000 rw-p 00000000 00:00 0
7f349afec000-7f349afef000 r-xp 00000000 00:6b 2236                       /lib64/libdl-2.25.so
7f349afef000-7f349b1ee000 ---p 00003000 00:6b 2236                       /lib64/libdl-2.25.so
7f349b1ee000-7f349b1ef000 r--p 00002000 00:6b 2236                       /lib64/libdl-2.25.so
7f349b1ef000-7f349b1f0000 rw-p 00003000 00:6b 2236                       /lib64/libdl-2.25.so
7f349b1f0000-7f349b38f000 r-xp 00000000 00:6b 2234                       /lib64/libc-2.25.so
7f349b38f000-7f349b58f000 ---p 0019f000 00:6b 2234                       /lib64/libc-2.25.so
7f349b58f000-7f349b593000 r--p 0019f000 00:6b 2234                       /lib64/libc-2.25.so
7f349b593000-7f349b595000 rw-p 001a3000 00:6b 2234                       /lib64/libc-2.25.so
7f349b595000-7f349b599000 rw-p 00000000 00:00 0
7f349b599000-7f349b5af000 r-xp 00000000 00:6b 1377                       /lib64/libgcc_s.so.1
7f349b5af000-7f349b7ae000 ---p 00016000 00:6b 1377                       /lib64/libgcc_s.so.1
7f349b7ae000-7f349b7af000 rw-p 00015000 00:6b 1377                       /lib64/libgcc_s.so.1
7f349b7af000-7f349b8c1000 r-xp 00000000 00:6b 2237                       /lib64/libm-2.25.so
7f349b8c1000-7f349bac0000 ---p 00112000 00:6b 2237                       /lib64/libm-2.25.so
7f349bac0000-7f349bac1000 r--p 00111000 00:6b 2237                       /lib64/libm-2.25.so
7f349bac1000-7f349bac2000 rw-p 00112000 00:6b 2237                       /lib64/libm-2.25.so
7f349bac2000-7f349bc34000 r-xp 00000000 00:6b 1613                       /usr/lib64/libstdc++.so.6.0.21
7f349bc34000-7f349be34000 ---p 00172000 00:6b 1613                       /usr/lib64/libstdc++.so.6.0.21
7f349be34000-7f349be3e000 r--p 00172000 00:6b 1613                       /usr/lib64/libstdc++.so.6.0.21
7f349be3e000-7f349be40000 rw-p 0017c000 00:6b 1613                       /usr/lib64/libstdc++.so.6.0.21
7f349be40000-7f349be44000 rw-p 00000000 00:00 0
7f349be44000-7f349be5d000 r-xp 00000000 00:6b 2242                       /lib64/libpthread-2.25.so
7f349be5d000-7f349c05d000 ---p 00019000 00:6b 2242                       /lib64/libpthread-2.25.so
7f349c05d000-7f349c05e000 r--p 00019000 00:6b 2242                       /lib64/libpthread-2.25.so
7f349c05e000-7f349c05f000 rw-p 0001a000 00:6b 2242                       /lib64/libpthread-2.25.so
7f349c05f000-7f349c063000 rw-p 00000000 00:00 0
7f349c063000-7f349c078000 r-xp 00000000 00:6b 64                         /lib64/libz.so.1.2.8
7f349c078000-7f349c277000 ---p 00015000 00:6b 64                         /lib64/libz.so.1.2.8
7f349c277000-7f349c278000 rw-p 00014000 00:6b 64                         /lib64/libz.so.1.2.8
7f349c278000-7f349c4a8000 r-xp 00000000 00:6b 60                         /lib64/libcrypto.so.1.0.0
7f349c4a8000-7f349c6a8000 ---p 00230000 00:6b 60                         /lib64/libcrypto.so.1.0.0
7f349c6a8000-7f349c6cf000 rw-p 00230000 00:6b 60                         /lib64/libcrypto.so.1.0.0
7f349c6cf000-7f349c6d3000 rw-p 00000000 00:00 0
7f349c6d3000-7f349c73f000 r-xp 00000000 00:6b 311                        /lib64/libssl.so.1.0.0
7f349c73f000-7f349c93e000 ---p 0006c000 00:6b 311                        /lib64/libssl.so.1.0.0
7f349c93e000-7f349c949000 rw-p 0006b000 00:6b 311                        /lib64/libssl.so.1.0.0
7f349c949000-7f349c96d000 r-xp 00000000 00:6b 105                        /lib64/ld-2.25.so
7f349cb5e000-7f349cb65000 rw-p 00000000 00:00 0
7f349cb69000-7f349cb6c000 rw-p 00000000 00:00 0
7f349cb6c000-7f349cb6d000 r--p 00023000 00:6b 105                        /lib64/ld-2.25.so
7f349cb6d000-7f349cb6f000 rw-p 00024000 00:6b 105                        /lib64/ld-2.25.so
7ffcc7606000-7ffcc7627000 rw-p 00000000 00:00 0                          [stack]
7ffcc77e4000-7ffcc77e6000 r--p 00000000 00:00 0                          [vvar]
7ffcc77e6000-7ffcc77e8000 r-xp 00000000 00:00 0                          [vdso]
Aborted
[root@dind h2o]#
```

**Comment by glensc** [comment]
```

root@dind ~/h2o# gdb --args h2o -c h2o.conf
GNU gdb (GDB) 8.0-1 (PLD Linux)
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pld-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from h2o...Reading symbols from /usr/lib/debug/usr/sbin/h2o.debug...done.
done.
(gdb) r
Starting program: /usr/sbin/h2o -c h2o.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
*** Error in `/usr/sbin/h2o': munmap_chunk(): invalid pointer: 0x0000000000587090 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7447c)[0x7ffff66f447c]
/lib64/libc.so.6(+0x7aaae)[0x7ffff66faaae]
/usr/sbin/h2o[0x4570b3]
/usr/sbin/h2o(h2o_configurator_apply_commands+0xa6)[0x43a556]
/usr/sbin/h2o(h2o_configurator_apply+0x41)[0x43dee1]
/usr/sbin/h2o(main+0x5b1)[0x4279f1]
/lib64/libc.so.6(__libc_start_main+0xf1)[0x7ffff66a05a1]
/usr/sbin/h2o(_start+0x2a)[0x42818a]
======= Memory map: ========

======= Memory map: ========
00400000-006c6000 r-xp 00000000 00:6b 7150                               /usr/sbin/h2o
008c5000-008c7000 r--p 002c5000 00:6b 7150                               /usr/sbin/h2o
008c7000-008cb000 rw-p 002c7000 00:6b 7150                               /usr/sbin/h2o
008cb000-00a47000 rw-p 00000000 00:00 0                                  [heap]
7ffff626a000-7ffff6275000 r-xp 00000000 00:6b 2241                       /lib64/libnss_files-2.25.so
7ffff6275000-7ffff6474000 ---p 0000b000 00:6b 2241                       /lib64/libnss_files-2.25.so
7ffff6474000-7ffff6475000 r--p 0000a000 00:6b 2241                       /lib64/libnss_files-2.25.so
7ffff6475000-7ffff6476000 rw-p 0000b000 00:6b 2241                       /lib64/libnss_files-2.25.so
7ffff6476000-7ffff647c000 rw-p 00000000 00:00 0
7ffff647c000-7ffff647f000 r-xp 00000000 00:6b 2236                       /lib64/libdl-2.25.so
7ffff647f000-7ffff667e000 ---p 00003000 00:6b 2236                       /lib64/libdl-2.25.so
7ffff667e000-7ffff667f000 r--p 00002000 00:6b 2236                       /lib64/libdl-2.25.so
7ffff667f000-7ffff6680000 rw-p 00003000 00:6b 2236                       /lib64/libdl-2.25.so
7ffff6680000-7ffff681f000 r-xp 00000000 00:6b 2234                       /lib64/libc-2.25.so
7ffff681f000-7ffff6a1f000 ---p 0019f000 00:6b 2234                       /lib64/libc-2.25.so
7ffff6a1f000-7ffff6a23000 r--p 0019f000 00:6b 2234                       /lib64/libc-2.25.so
7ffff6a23000-7ffff6a25000 rw-p 001a3000 00:6b 2234                       /lib64/libc-2.25.so
7ffff6a25000-7ffff6a29000 rw-p 00000000 00:00 0
7ffff6a29000-7ffff6a3f000 r-xp 00000000 00:6b 1377                       /lib64/libgcc_s.so.1
7ffff6a3f000-7ffff6c3e000 ---p 00016000 00:6b 1377                       /lib64/libgcc_s.so.1
7ffff6c3e000-7ffff6c3f000 rw-p 00015000 00:6b 1377                       /lib64/libgcc_s.so.1
7ffff6c3f000-7ffff6d51000 r-xp 00000000 00:6b 2237                       /lib64/libm-2.25.so
7ffff6d51000-7ffff6f50000 ---p 00112000 00:6b 2237                       /lib64/libm-2.25.so
7ffff6f50000-7ffff6f51000 r--p 00111000 00:6b 2237                       /lib64/libm-2.25.so
7ffff6f51000-7ffff6f52000 rw-p 00112000 00:6b 2237                       /lib64/libm-2.25.so
7ffff6f52000-7ffff70c4000 r-xp 00000000 00:6b 1613                       /usr/lib64/libstdc++.so.6.0.21
7ffff70c4000-7ffff72c4000 ---p 00172000 00:6b 1613                       /usr/lib64/libstdc++.so.6.0.21
7ffff72c4000-7ffff72ce000 r--p 00172000 00:6b 1613                       /usr/lib64/libstdc++.so.6.0.21
7ffff72ce000-7ffff72d0000 rw-p 0017c000 00:6b 1613                       /usr/lib64/libstdc++.so.6.0.21
7ffff72d0000-7ffff72d4000 rw-p 00000000 00:00 0
7ffff72d4000-7ffff72ed000 r-xp 00000000 00:6b 2242                       /lib64/libpthread-2.25.so
7ffff72ed000-7ffff74ed000 ---p 00019000 00:6b 2242                       /lib64/libpthread-2.25.so
7ffff74ed000-7ffff74ee000 r--p 00019000 00:6b 2242                       /lib64/libpthread-2.25.so
7ffff74ee000-7ffff74ef000 rw-p 0001a000 00:6b 2242                       /lib64/libpthread-2.25.so
7ffff74ef000-7ffff74f3000 rw-p 00000000 00:00 0
7ffff74f3000-7ffff7508000 r-xp 00000000 00:6b 64                         /lib64/libz.so.1.2.8
7ffff7508000-7ffff7707000 ---p 00015000 00:6b 64                         /lib64/libz.so.1.2.8
7ffff7707000-7ffff7708000 rw-p 00014000 00:6b 64                         /lib64/libz.so.1.2.8
7ffff7708000-7ffff7938000 r-xp 00000000 00:6b 60                         /lib64/libcrypto.so.1.0.0
7ffff7938000-7ffff7b38000 ---p 00230000 00:6b 60                         /lib64/libcrypto.so.1.0.0
7ffff7b38000-7ffff7b5f000 rw-p 00230000 00:6b 60                         /lib64/libcrypto.so.1.0.0
7ffff7b5f000-7ffff7b63000 rw-p 00000000 00:00 0
7ffff7b63000-7ffff7bcf000 r-xp 00000000 00:6b 311                        /lib64/libssl.so.1.0.0
7ffff7bcf000-7ffff7dce000 ---p 0006c000 00:6b 311                        /lib64/libssl.so.1.0.0
7ffff7dce000-7ffff7dd9000 rw-p 0006b000 00:6b 311                        /lib64/libssl.so.1.0.0
7ffff7dd9000-7ffff7dfd000 r-xp 00000000 00:6b 105                        /lib64/ld-2.25.so
7ffff7fea000-7ffff7ff1000 rw-p 00000000 00:00 0
7ffff7ff5000-7ffff7ff8000 rw-p 00000000 00:00 0

7ffff7ff8000-7ffff7ffa000 r--p 00000000 00:00 0                          [vvar]
7ffff7ffa000-7ffff7ffc000 r-xp 00000000 00:00 0                          [vdso]
7ffff7ffc000-7ffff7ffd000 r--p 00023000 00:6b 105                        /lib64/ld-2.25.so
7ffff7ffd000-7ffff7fff000 rw-p 00024000 00:6b 105                        /lib64/ld-2.25.so
7ffffffde000-7ffffffff000 rw-p 00000000 00:00 0                          [stack]

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      }
(gdb)

(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff66b562a in __GI_abort () at abort.c:89
#2  0x00007ffff66f4481 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ffff67f0b48 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff66faaae in malloc_printerr (action=3, str=0x7ffff67f0ba0 "munmap_chunk(): invalid pointer", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5077
#4  0x00000000004570b3 in on_config_enter (_self=0x903af0, ctx=<optimized out>, node=<optimized out>) at /home/users/glen/rpm/packages/BUILD.x86_64-linux/h2o-2.2.2/lib/handler/configurator/proxy.c:305
#5  0x000000000043a556 in setup_configurators (node=<optimized out>, is_enter=1, ctx=0x917e80) at /home/users/glen/rpm/packages/BUILD.x86_64-linux/h2o-2.2.2/lib/core/configurator.c:112
#6  h2o_configurator_apply_commands (ctx=ctx@entry=0x917e80, node=node@entry=0x9181e0, flags_mask=flags_mask@entry=1, ignore_commands=ignore_commands@entry=0x0)
    at /home/users/glen/rpm/packages/BUILD.x86_64-linux/h2o-2.2.2/lib/core/configurator.c:149
#7  0x000000000043dee1 in h2o_configurator_apply (config=config@entry=0x8ca1e0 <conf>, node=node@entry=0x9181e0, dry_run=0) at /home/users/glen/rpm/packages/BUILD.x86_64-linux/h2o-2.2.2/lib/core/configurator.c:1008
#8  0x00000000004279f1 in main (argc=<optimized out>, argv=<optimized out>) at /home/users/glen/rpm/packages/BUILD.x86_64-linux/h2o-2.2.2/src/main.c:2080
(gdb)
```

**Comment by glensc** [comment]
compile with debug flags. just shorter death.

```

root@dind ~/h2o# gdb --args h2o -c h2o.conf
GNU gdb (GDB) 8.0-1 (PLD Linux)
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pld-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from h2o...done.
(gdb) r
Starting program: /usr/sbin/h2o -c h2o.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff64fb584 in __GI___libc_free (mem=0x586b38) at malloc.c:2946
2946      ar_ptr = arena_for_chunk (p);
(gdb) bt
#0  0x00007ffff64fb584 in __GI___libc_free (mem=0x586b38) at malloc.c:2946
#1  0x00000000004556e3 in on_config_enter (_self=0x907af0, ctx=<optimized out>, node=<optimized out>) at /home/users/glen/rpm/packages/BUILD.x86_64-linux/h2o-2.2.2/lib/handler/configurator/proxy.c:305
#2  0x0000000000439efe in setup_configurators (node=<optimized out>, is_enter=1, ctx=0x91be80) at /home/users/glen/rpm/packages/BUILD.x86_64-linux/h2o-2.2.2/lib/core/configurator.c:112
#3  h2o_configurator_apply_commands (ctx=ctx@entry=0x91be80, node=node@entry=0x91c1e0, flags_mask=flags_mask@entry=1, ignore_commands=ignore_commands@entry=0x0)
    at /home/users/glen/rpm/packages/BUILD.x86_64-linux/h2o-2.2.2/lib/core/configurator.c:149
#4  0x000000000043d771 in h2o_configurator_apply (config=config@entry=0x8ce1e0 <conf>, node=node@entry=0x91c1e0, dry_run=0) at /home/users/glen/rpm/packages/BUILD.x86_64-linux/h2o-2.2.2/lib/core/configurator.c:1008
#5  0x000000000042766a in main (argc=<optimized out>, argv=<optimized out>) at /home/users/glen/rpm/packages/BUILD.x86_64-linux/h2o-2.2.2/src/main.c:2080
(gdb)
```

**Comment by glensc** [comment]
nevermind. caused by broken patch
