### ISSUE TITLE
Can't get Server to work with grav-cms

### ISSUE THREAD

**Issue by DanielSokil** [h2o/h2o#1507]
My Error Log File
```
starting new worker 32649
[INFO] raised RLIMIT_NOFILE to 1048576
h2o server (pid:32649) is ready to serve requests
[lib/handler/fastcgi.c] in request:/index.php/:PHP Fatal error:  Uncaught RuntimeException: Opening file for writing failed on error fopen(/var/www/html/cache//compiled/files/b296ac48b18c22fb9ad19958ded5d09f.yaml.php): failed to open stream: Permission denied in /var/www/html/vendor/rockettheme/toolbox/File/src/File.php:202
```
Stack trace:
```
#0 /var/www/html/vendor/rockettheme/toolbox/File/src/File.php(320): RocketTheme\Toolbox\File\File->lock()
#1 /var/www/html/vendor/rockettheme/toolbox/File/src/PhpFile.php(31): RocketTheme\Toolbox\File\File->save(Array)
#2 /var/www/html/system/src/Grav/Common/File/CompiledFile.php(67): RocketTheme\Toolbox\File\PhpFile->save(Array)
#3 /var/www/html/system/src/Grav/Common/Config/Setup.php(178): Grav\Common\File\CompiledYamlFile->content()
#4 /var/www/html/system/src/Grav/Common/Processors/SiteSetupProcessor.php(18): Grav\Common\Config\Setup->init()
#5 /var/www/html/system/src/Grav/Common/Grav.php(132): Grav\Common\Processors\SiteSetupProcessor->process()
#6 /var/www/html/system/src/Grav/Common/Grav.php(379): Grav\Common\Grav->Grav\Common\{clos in /var/www/html/system/src/Grav/Common/File/CompiledFile.php on line 83
```

My h20 conf File
```
hosts:
  "localhost:80":
    listen:
      port: 80
      host: 0.0.0.0
    paths:
      "/":
        file.dir: /var/www/html
        redirect:
          url: /index.php/
          internal: YES
          status: 307

file.custom-handler:
  extension: .php
  fastcgi.spawn: "PHP_FCGI_CHILDREN=10 exec /usr/bin/php-cgi"

access-log: /var/log/h2o/access.log
error-log: /var/log/h2o/error.log
pid-file: /var/run/h2o/h2o.pid
#http2-reprioritize-blocking-assets: ON
```

**Comment by TheDecryptor** [comment]
If you don't supply a user for the FCGI process to run under, it'll inherit it from the server process (Which, unless you've configured it, will be `nobody`)

That user account should be pretty limited by default, and won't have write permissions to the folder where the CMS is trying to write out cache files. I'd suggest creating a separate user account just for the CMS, and telling h2o to [run the php process as that user](https://h2o.examp1e.net/configure/fastcgi_directives.html#fastcgi.spawn), then you can adjust the FS permissions to allow that account R/W access to the folders the CMS needs.

**Comment by DanielSokil** [comment]
Thank You!
