### ISSUE TITLE
received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by yangdebin** [h2o/h2o#2078]
Thread 19 received signal SIGSEGV, Segmentation fault.
[Switching to LWP 3793]
0x0000000002c508c4 in h2o_setup_next_ostream (slot=0x7fb8a0a3a0, req=0x7fb8a0a118) at h2o/include/h2o.h:2154
2154    h2o/include/h2o.h: No such file or directory.
(gdb) bt
#0  0x0000000002c508c4 in h2o_setup_next_ostream (slot=0x7fb8a0a3a0, req=0x7fb8a0a118) at h2o/include/h2o.h:2154
#1  h2o_start_response (req=0x7fb8a0a118, generator=generator@entry=0x38c6040 <process_ready_req_item(server_context_t*, http_request_wrapper_t*)::generator>)
    at h2o/lib/core/request.c:480
#2  0x0000000002879228 in process_ready_req_item (mgr=0x38c5d80 <server_ctx>, req_w=0x7f51523218) at viwi_receiver.cpp:868
#3  on_process_ready_req_list (receiver=<optimized out>, messages=0x7f8aebe280) at viwi_receiver.cpp:912
#4  0x0000000002c40224 in queue_cb (queue=0x7fb98073e0) at h2o/lib/common/multithread.c:64
#5  on_read (sock=<optimized out>, err=<optimized out>) at h2o/lib/common/multithread.c:91
#6  0x0000000002c4118c in read_on_ready (sock=0x7fb7c0fb10) at h2o/lib/common/socket/evloop.c.h:248
#7  run_socket (sock=sock@entry=0x7fb7c0fb10) at h2o/lib/common/socket/evloop.c.h:517
#8  0x0000000002c414a0 in run_pending (loop=loop@entry=0x7fb9a07f30) at h2o/lib/common/socket/evloop.c.h:550
#9  0x0000000002c45524 in h2o_evloop_run (loop=0x7fb9a07f30, max_wait=max_wait@entry=2147483647) at h2o/lib/common/socket/evloop.c.h:603
#10 0x000000000287a1c0 in server_loop (_thread_index=0x0) at viwi_receiver.cpp:1015
#11 0x0000007fbe770a8c in __tsan_thread_start_func (arg=0x7f8ceba128)
    at libsanitizer/tsan/tsan_interceptors.cc:890
#12 0x0000007fbddbfef8 in ?? () from target:/lib/libpthread.so.0
#13 0x0000007f8ceba140 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

I'm used sanitizer thread check program. Discovery crash issue.

**Comment by chenbd** [comment]
@yangdebin have you dig into this issue?
IMO this maybe caused by misuse or misunderstanding of the library.
