### ISSUE TITLE
update_idle_timeout: Assertion `h2o_timer_is_linked(&conn->_timeout_entry)' failed

### ISSUE THREAD

**Issue by bortzmeyer** [h2o/h2o#2454]
Running h2o from dnsdist https://dnsdist.org/ I get random (?) occurrences of:

```
 dnsdist: /home/stephane/DoH/h2o/h2o-2.3.0-beta2/lib/http2/connection.c:158: update_idle_timeout: Assertion `h2o_timer_is_linked(&conn->_timeout_entry)' failed.
```

I notice that 2.3 is beta for more than a year. Should I downgrade to 2.2?

This issue has some ressemblance with #2149 (but I use Linux).

```
%  h2o -v
h2o version 2.3.0-beta2
OpenSSL: OpenSSL 1.1.1g  21 Apr 2020

% uname -a
Linux radia.bortzmeyer.org 5.8.5-arch1-1 #1 SMP PREEMPT Thu, 27 Aug 2020 18:53:02 +0000 x86_64 GNU/Linux

% gcc --version
gcc (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by kazuho** [comment]
Thank you for reporting the issue.
* Regarding stability, I think that master should provide the best set of features & stability assuming that you'd be using HTTP/1 or 2.
* Do you happen to have a stack trace? By default, the standalone server of h2o will try to emit the stack trace alongside the assertion failure that you have posted. Honestly I'm not sure how we could hit this assertion. Any information (e.g., stack trace, configuration file) will be welcome.

**Comment by bortzmeyer** [comment]
@kazuho By "master", you mean git master branch, the very last developments?

**Comment by cbay** [comment]
I hit this regularly (multiple times a day). I'm on [kazuho/tunnel-reuse-req-resp-streams](https://github.com/h2o/h2o/tree/kazuho/tunnel-reuse-req-resp-streams). Here's a stack trace:

```
#0  0x00007f895ebcb7bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f895ebb6535 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f895ebb640f in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f895ebc4102 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007f895a6c69a1 in update_idle_timeout (conn=0x616000cc2780) at /home/cbay/h2o/lib/http2/connection.c:157
#5  update_idle_timeout (conn=0x616000cc2780) at /home/cbay/h2o/lib/http2/connection.c:157
#6  0x00007f895a6c8dd0 in h2o_http2_conn_unregister_stream (conn=conn@entry=0x616000cc2780, stream=stream@entry=0x61a001439a80)
    at /home/cbay/h2o/lib/http2/connection.c:364
#7  0x00007f895a6cedd1 in h2o_http2_stream_close (conn=0x616000cc2780, stream=0x61a001439a80) at /home/cbay/h2o/lib/http2/stream.c:70
#8  0x00007f895a6c6e5c in close_connection_now (conn=<optimized out>) at /home/cbay/h2o/lib/http2/connection.c:374
#9  close_connection_now (conn=0x616000cc2780) at /home/cbay/h2o/lib/http2/connection.c:368
#10 0x00007f895af998e8 in uv__run_timers (loop=loop@entry=0x618000103c80) at src/timer.c:177
#11 0x00007f895af9da2d in uv_run (loop=0x618000103c80, mode=mode@entry=UV_RUN_DEFAULT) at src/unix/core.c:376
#12 0x00007f895aee3fd0 in __pyx_f_6uvloop_4loop_4Loop___run (__pyx_v_self=0x7f89572be810, __pyx_v_mode=UV_RUN_DEFAULT) at uvloop/loop.c:14618
#13 0x00007f895af53890 in __pyx_f_6uvloop_4loop_4Loop__run (__pyx_v_self=0x7f89572be810, __pyx_v_mode=UV_RUN_DEFAULT) at uvloop/loop.c:15006
#14 0x00007f895af225bd in __pyx_pf_6uvloop_4loop_4Loop_24run_forever (__pyx_v_self=0x7f89572be810) at uvloop/loop.c:27613
#15 __pyx_pw_6uvloop_4loop_4Loop_25run_forever (__pyx_v_self=0x7f89572be810, unused=<optimized out>) at uvloop/loop.c:27434
#16 0x00007f895aecd396 in __Pyx_PyObject_CallMethO (arg=0x0, func=0x7f8957363860) at uvloop/loop.c:166801
#17 __Pyx_PyObject_CallNoArg (func=0x7f8957363860) at uvloop/loop.c:35755
#18 0x00007f895af51503 in __pyx_pf_6uvloop_4loop_4Loop_44run_until_complete (__pyx_v_future=0x7f8957384860, __pyx_v_self=<optimized out>) at uvloop/loop.c:29214
#19 __pyx_pw_6uvloop_4loop_4Loop_45run_until_complete (__pyx_v_self=<optimized out>, __pyx_v_future=<optimized out>) at uvloop/loop.c:28812
```

**Comment by cwyang** [comment]
Refer this issue: https://github.com/h2o/h2o/pull/2844

Kind regards,
Chul-Woong

**Comment by dch** [comment]
@kazuho it's problematic for projects like dnsdist who are using this as a library via libh2o to rely on master branch for software that's likely to live almost unchanged in user package repos for months or years.

Is there an intention to cut a release at any future point, or has h2o project effectively usinga "run-from-master" model? There has been an enormous amount of changes & improvements since 2.3 beta that people are missing out on.
