### ISSUE TITLE
Crash during websocket establishment over proxy

### ISSUE THREAD

**Issue by cbay** [h2o/h2o#2703]
Tested on the current master (35401aeb71bd9b8f97e543c524aae50af24e0978), although the faulty commit was bisected to 90a1f65d658c62fdae59bf520dcbfe8eba49f0ea.

`h2o.conf`:

```
hosts:
  "*":
    listen:
      port: 8080
    paths:
      "/":
        proxy.reverse.url: http://127.0.0.1:8090/
        proxy.tunnel: ON
```

Crash, as seen by gdb:

```
0x00005555555e4ce2 in h2o_socket_get_loop (_sock=0x0) at /home/cbay/h2o/lib/common/socket/evloop.c.h:365
365         return sock->loop;
(gdb) bt
#0  0x00005555555e4ce2 in h2o_socket_get_loop (_sock=0x0) at /home/cbay/h2o/lib/common/socket/evloop.c.h:365
#1  0x00005555556305e0 in tunnel_reset_timeout (tunnel=0x7ffff0005cd0) at /home/cbay/h2o/lib/http1.c:835
#2  0x0000555555630714 in tunnel_on_server_read (_tunnel=0x7ffff0005c70, err=0x0, bytes=0x7ffff0006974, len=4) at /home/cbay/h2o/lib/http1.c:862
#3  0x00005555556326b7 in call_on_read (tunnel=0x7ffff0005c70, err=0x0, bytes=0x7ffff0006974, len=4) at /home/cbay/h2o/lib/tunnel.c:71
#4  0x000055555563273b in socket_tunnel_proceed_read (_tunnel=0x7ffff0005c70) at /home/cbay/h2o/lib/tunnel.c:85
#5  0x0000555555632927 in h2o_socket_tunnel_start (tunnel=0x7ffff0005c70, bytes_to_consume=240) at /home/cbay/h2o/lib/tunnel.c:133
#6  0x00005555555d403a in on_head (sock=0x7ffff00054e0, err=0x0) at /home/cbay/h2o/lib/common/http1client.c:444
#7  0x00005555555e48b1 in read_on_ready (sock=0x7ffff00054e0) at /home/cbay/h2o/lib/common/socket/evloop.c.h:251
#8  0x00005555555e534c in run_socket (sock=0x7ffff00054e0) at /home/cbay/h2o/lib/common/socket/evloop.c.h:540
#9  0x00005555555e54a7 in run_pending (loop=0x7ffff0000b60) at /home/cbay/h2o/lib/common/socket/evloop.c.h:573
#10 0x00005555555e5682 in h2o_evloop_run (loop=0x7ffff0000b60, max_wait=2147483647) at /home/cbay/h2o/lib/common/socket/evloop.c.h:625
#11 0x00005555557490d6 in run_loop (_thread_index=0x1) at /home/cbay/h2o/src/main.c:2841
#12 0x00007ffff7a94299 in start_thread () from /usr/lib/libpthread.so.0
#13 0x00007ffff79bd053 in clone () from /usr/lib/libc.so.6
```

Python script to trigger the crash (works as both server and client):

```python
import asyncio
import uvloop
import aiohttp
import aiohttp.web

async def handler(request):
    client = aiohttp.web.WebSocketResponse()
    await client.prepare(request)
    await client.close()

async def start():
    # Setup server.
    app = aiohttp.web.Application()
    app.router.add_route('GET', '/', handler)

    runner = aiohttp.web.AppRunner(app)
    await runner.setup()

    server = aiohttp.web.TCPSite(runner, '127.0.0.1', 8090)
    await server.start()

    # Start client.
    async with aiohttp.ClientSession() as client:
        await client.ws_connect('ws://localhost:8080/')

if __name__ == '__main__':
    asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
    loop = asyncio.get_event_loop()
    loop.run_until_complete(start())
```

**Comment by cbay** [comment]
This crash doesn't occur in the tunnel-reuse-req-resp-streams branch (#2607). I assume this is the way forward anyway, so I guess that issue can be closed once it's been pulled.
