### ISSUE TITLE
Segmentation fault sk_free  at stack/stack.c:290

### ISSUE THREAD

**Issue by Roze** [h2o/h2o#315]
This kinda seems LibreSSL fault but reporting anyways:

	Core was generated by `/data/h2o/bin/h2o -c /data/h2o/h2o.conf'.
	Program terminated with signal 11, Segmentation fault.
	#0  sk_free (st=0x200000000) at stack/stack.c:290
	290             free(st->data);

	(gdb) bt full
	#0  sk_free (st=0x200000000) at stack/stack.c:290
	No locals.
	#1  0x00000000004a2471 in int_free_ex_data (class_index=<optimized out>, obj=0x5753580, ad=0x5753650) at ex_data.c:530
			mx = 0
			i = <optimized out>
			item = 0x7f1f1427ac00
			ptr = <optimized out>
			storage = <optimized out>
	#2  0x0000000000491584 in SSL_SESSION_free (ss=0x5753580) at ssl_sess.c:698
	No locals.
	#3  SSL_SESSION_free (ss=0x5753580) at ssl_sess.c:687
			i = <optimized out>
	#4  0x000000000048ebd5 in SSL_free (s=0x36c89e0) at ssl_lib.c:531
			i = <optimized out>
	#5  0x00000000004474ac in destroy_ssl (ssl=0x271a380) at /data/install/h2o-1.2.0/lib/common/socket.c:208
	No locals.
	#6  0x0000000000447504 in dispose_socket (sock=0x3d4f8b0, status=<optimized out>) at /data/install/h2o-1.2.0/lib/common/socket.c:220
			close_cb = <optimized out>
			close_cb_data = <optimized out>
	#7  0x0000000000446ce9 in on_write_complete (status=0, sock=0x3d4f8b0) at /data/install/h2o-1.2.0/lib/common/socket.c:378
			cb = <optimized out>
	#8  run_socket (sock=0x3d4f8b0) at /data/install/h2o-1.2.0/lib/common/socket/evloop.c.h:461
			status = 0
	#9  run_pending (loop=<optimized out>) at /data/install/h2o-1.2.0/lib/common/socket/evloop.c.h:477
			sock = 0x3d4f8b0
	#10 0x0000000000447a45 in h2o_timeout__do_post_callback (loop=loop@entry=0xff42a0) at /data/install/h2o-1.2.0/lib/common/socket/evloop.c.h:519
	No locals.
	#11 0x0000000000449d9e in h2o_timeout_run (loop=loop@entry=0xff42a0, timeout=timeout@entry=0x7fff9f46f1f0, now=<optimized out>) at /data/install/h2o-1.2.0/lib/common/timeout.c:36
			entry = <optimized out>
			max_registered_at = 1431877187495
	#12 0x0000000000447978 in h2o_evloop_run (loop=0xff42a0) at /data/install/h2o-1.2.0/lib/common/socket/evloop.c.h:495
			timeout = 0x7fff9f46f1f0
			node = 0x7fff9f46f1f8
			__PRETTY_FUNCTION__ = "h2o_evloop_run"
	#13 0x0000000000473a02 in run_loop (_thread_index=_thread_index@entry=0x0) at /data/install/h2o-1.2.0/src/main.c:1205
			thread_index = 0
			listeners = 0x7fff9f46f150
			i = <optimized out>
	#14 0x00000000004433da in main (argc=<optimized out>, argv=<optimized out>) at /data/install/h2o-1.2.0/src/main.c:1610
			cmd = 0x7fff9f4718db "/data/h2o/bin/h2o"
			opt_config_file = <optimized out>
			error_log_fd = <optimized out>
			__PRETTY_FUNCTION__ = "main"
			i = 4

**Comment by kazuho** [comment]
This looks bad.

I am not sure what the cause of the issue is, but have added code that resets the pointers to NULL after disposing them, so that more appropriate error messages will be displayed in case it is the problem within H2O.
