### ISSUE TITLE
Python pip - wrong location OS X

### ISSUE THREAD

**Issue by lettergram** [h2o/h2o#703]
I recently upgraded to El Capitan and they have the rootless permissions (i.e. I cannot edit /System files). 

The current way to install h2o for python requires access to those files - which it does not have. Leading to the following exceptions:

    Exception:
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 211, in main status = self.run(options, args)
      File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 311, in run root=options.root_path,
      File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 646, in install **kwargs
      File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 803, in install self.move_wheel_files(self.source_dir, root=root)
      File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 998, in move_wheel_files isolated=self.isolated,
      File "/Library/Python/2.7/site-packages/pip/wheel.py", line 371, in move_wheel_files clobber(source, dest, False, fixer=fixer, filter=filter)
      File "/Library/Python/2.7/site-packages/pip/wheel.py", line 310, in clobber ensure_dir(destdir)
      File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 71, in ensure_dir os.makedirs(path)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs mkdir(name, mode)
    OSError: [Errno 1] Operation not permitted: '/System/Library/Frameworks/Python.framework/Versions/2.7/h2o_data'

**Comment by lettergram** [comment]
I found a work around:

http://apple.stackexchange.com/questions/209572/how-to-use-pip-after-the-el-capitan-max-os-x-upgrade

Probably not even H2O's issue, but it should be documented.
