### ISSUE TITLE
Running h2o with -fsanitizer=address

### ISSUE THREAD

**Issue by mingodad** [h2o/h2o#705]
Hello !
I could not find the problem yet but I suspect that after this other problems can follow.
Cheers !

I built h2o with:
```
cmake \
    -DWITH_BUNDLED_SSL=ON \
    -DCMAKE_C_FLAGS="-march=native -O2 -g -fsanitize=address" \
    -DCMAKE_DL_LIBS="-lasan" \
    -DWITH_MRUBY=ON
```
Then run it as:
```
./h2o --conf=examples/h2o_mruby/h2o.conf
```
Then made a request http://127.0.0.1:8080/hello and got this:
```
=================================================================
==2546==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000006b4368 at pc 0x52f431 bp 0x7ffb9013a510 sp 0x7ffb9013a508
READ of size 8 at 0x0000006b4368 thread T7
    #0 0x52f430 in build_env_sort_header_cb /home/xxx/dev/c/web-servers/h2o/lib/handler/mruby.c:403
    #1 0x7ffb961b1344 (/lib/x86_64-linux-gnu/libc.so.6+0x3b344)
    #2 0x7ffb961b1221 (/lib/x86_64-linux-gnu/libc.so.6+0x3b221)
    #3 0x7ffb961b1221 (/lib/x86_64-linux-gnu/libc.so.6+0x3b221)
    #4 0x7ffb961b177b in qsort_r (/lib/x86_64-linux-gnu/libc.so.6+0x3b77b)
    #5 0x530884 in build_env /home/xxx/dev/c/web-servers/h2o/lib/handler/mruby.c:466
    #6 0x535a97 in on_req /home/xxx/dev/c/web-servers/h2o/lib/handler/mruby.c:581
    #7 0x486428 in process_hosted_request /home/xxx/dev/c/web-servers/h2o/lib/core/request.c:139
    #8 0x4b62d9 in handle_incoming_request /home/xxx/dev/c/web-servers/h2o/lib/http1.c:424
    #9 0x46902e in read_on_ready /home/xxx/dev/c/web-servers/h2o/lib/common/socket/evloop.c.h:242
    #10 0x46902e in run_socket /home/xxx/dev/c/web-servers/h2o/lib/common/socket/evloop.c.h:484
    #11 0x469477 in run_pending /home/xxx/dev/c/web-servers/h2o/lib/common/socket/evloop.c.h:501
    #12 0x46a403 in h2o_evloop_run /home/xxx/dev/c/web-servers/h2o/lib/common/socket/evloop.c.h:515
    #13 0x5263bb in run_loop /home/xxx/dev/c/web-servers/h2o/src/main.c:1270
    #14 0x7ffb96543181 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x8181)
    #15 0x7ffb9627047c in __clone (/lib/x86_64-linux-gnu/libc.so.6+0xfa47c)

0x0000006b4368 is located 56 bytes to the left of global variable '*.LC76' from '/home/xxx/dev/c/web-servers/h2o/lib/core/token.c' (0x6b43a0) of size 20
  '*.LC76' is ascii string 'content-disposition'
0x0000006b436b is located 0 bytes to the right of global variable '*.LC75' from '/home/xxx/dev/c/web-servers/h2o/lib/core/token.c' (0x6b4360) of size 11
  '*.LC75' is ascii string 'connection'
SUMMARY: AddressSanitizer: global-buffer-overflow /home/xxx/dev/c/web-servers/h2o/lib/handler/mruby.c:403 build_env_sort_header_cb
Shadow bytes around the buggy address:
  0x0000800ce810: f9 f9 f9 f9 00 f9 f9 f9 f9 f9 f9 f9 07 f9 f9 f9
  0x0000800ce820: f9 f9 f9 f9 00 07 f9 f9 f9 f9 f9 f9 00 00 f9 f9
  0x0000800ce830: f9 f9 f9 f9 00 00 f9 f9 f9 f9 f9 f9 00 06 f9 f9
  0x0000800ce840: f9 f9 f9 f9 00 00 00 04 f9 f9 f9 f9 04 f9 f9 f9
  0x0000800ce850: f9 f9 f9 f9 06 f9 f9 f9 f9 f9 f9 f9 00 06 f9 f9
=>0x0000800ce860: f9 f9 f9 f9 00 06 f9 f9 f9 f9 f9 f9 00[03]f9 f9
  0x0000800ce870: f9 f9 f9 f9 00 00 04 f9 f9 f9 f9 f9 00 00 01 f9
  0x0000800ce880: f9 f9 f9 f9 00 00 01 f9 f9 f9 f9 f9 00 07 f9 f9
  0x0000800ce890: f9 f9 f9 f9 00 00 01 f9 f9 f9 f9 f9 00 06 f9 f9
  0x0000800ce8a0: f9 f9 f9 f9 00 05 f9 f9 f9 f9 f9 f9 07 f9 f9 f9
  0x0000800ce8b0: f9 f9 f9 f9 05 f9 f9 f9 f9 f9 f9 f9 05 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Contiguous container OOB:fc
  ASan internal:           fe
Thread T7 created by T0 here:
    #0 0x7ffb96c9bc5a in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x23c5a)
    #1 0x4642f8 in h2o_multithread_create_thread /home/xxx/dev/c/web-servers/h2o/lib/common/multithread.c:184
    #2 0x7ffb96197ec4 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21ec4)

==2546==ABORTING
```

**Comment by kazuho** [comment]
Thank you for noticing the issue.  This was also a regression in 1.7.0-beta series.

Please reopen if the issue persists.
